### ISSUE TITLE
I can't put the verification on the project

### ISSUE THREAD

**Issue by ghost** [the-mighty-mo/FBIBot#16]
Hi, i make the donwload of your Project( Fbi bot for discord)  but i dont know were i put the verification code can you help me to make this download please, thanks for the attention :)

**Comment by bhall-ctre** [comment]
Hello criaK,

In the FBIBot folder, there should be a file called SecurityInfo.cs. In that file, you can plug in the three unique values to your local copy of the bot:

- Bot Token (required)
- Bot Discriminator (currently unused)
- Bot Client ID (currently unused)

You can create a new bot and get its token in the [Discord Developer Portal](https://discord.com/developers/applications).

Make sure that you do NOT commit the changes to that file and upload to GitHub. It is a major security breach, and Discord will delete your bot and force you to recreate the bot token. You can ensure that local changes to the file are not committed by using `git update-index --skip-worktree <file-list>`.

**Comment by the-mighty-mo** [comment]
Hello criaK,

In the FBIBot folder, there should be a file called SecurityInfo.cs. In that file, you can plug in the three unique values to your local copy of the bot:

- Bot Token (required)
- Bot Discriminator (currently unused)
- Bot Client ID (currently unused)

You can create a new bot and get its token in the [Discord Developer Portal](https://discord.com/developers/applications).

Make sure that you do NOT commit the changes to that file and upload to GitHub. It is a major security breach, and Discord will delete your bot and force you to recreate the bot token. You can ensure that local changes to the file are not committed by using `git update-index --skip-worktree <file-list>`.

(sorry for the duplicate notification)

**Comment by ghost** [comment]
Thanks the mighty-mo:)
